import {TStringsUtil} from "../type/TStringsUtil";

export const StringsUtil: TStringsUtil = {
  inicio: 'Início',
  novoLembrete: 'Novo Lembrete',
  contatos: 'Contatos',
  configuracoes: 'Configurações',
  meus: 'Meus',
  editar: 'Editar',
  excluir: 'Excluir',
  login: 'Login',
  nome: 'Nome',
  asteriscos: '******',
  fazerCadastro: 'Fazer cadastro',
  email: 'E-mail',
  digiteSeuNome: 'Digite seu nome',
  campoObrigatorio: 'Campo obrigatório',
  pending: 'Pendente',
  informeEmailValido: 'Informe um e-mail válido.',
  aguardeEnquantoRealizamosCadastro: 'Aguarde enquanto realizamos o seu cadastro.',
  cadastroRealizado: 'Seu cadastro foi realizado com sucesso.',
  digiteSeuEmail: 'Digite seu e-mail',
  digiteSuaSenha: 'Digite sua senha',
  senha: 'Senha',
  confirmaSenha: 'Confirmar senha',
  confirmeSuaSenha: 'Confirme sua senha',
  entrar: 'Entrar',
  criarConta: 'Criar conta',
  esqueciMinhaSenha: 'Esqueci minha senha',
  naoTenhoConta: 'Não tenho conta',
  jaCrieiMinhaConta: 'Já criei minha conta',
  filtrar: 'Filtrar',
  tokenExpirou: 'Token expirou',
  semConexaoComServidor: 'Sem conexão com o servidor',
  criarNovoContato: 'Criar novo contato',
  criarNovoLembrete: 'Criar novo lembrete'
};
