export type TAssetsUtil = {
  homeSVG: string,
  homeAzulSVG: string,
  usersSVG: string,
  usersAzulSVG: string,
  confSVG: string,
  confAzulSVG: string,
  gSVG: string,
  usergSVG: string,
  searchSVG: string,
  filterSVG: string,
  emailSVG: string,
  whatsappSVG: string,
  closeCircleSVG: string,
  telegramSVG: string,
  gFabSVG: string,
  editSVG: string,
  trashSVG: string,
  glSVG: string,
  envelopeSVG: string,
  eyeSVG: string,
  eyeSlashSVG: string,
  logoSVG: string,
  voltarSVG: string,
  setaAzulCimaSVG: string,
  setaAzulBaixoSVG: string,
  pendenteSVG: string,
}
